name: Register Device
on:
  workflow_dispatch:
    inputs:
      device_name:
        required: true
        description: 'Device Name'
        default: ''
      device_type:
        required: true
        description: 'Device Type'
        default: ''
      is_personal_device:
        required: true
        description: 'Is personal device?'
        deprecationMessage: 'Hello world!'
        default: true
      device_uuid:
        required: true
        description: 'Device UUID'
        default: ''
jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Register Device
        env:
          DEVICE_NAME: ${{ github.event.inputs.device_name }}
          DEVICE_TYPE: ${{ github.event.inputs.device_type }}
          DEVICE_PERSONAL: ${{ github.event.inputs.is_personal_device }}
          DEVICE_UUID: ${{ github.event.inputs.device_uuid }}
        run: |
          echo ${{ github.event.inputs.device_name }} ${{ github.event.inputs.device_type }}
