name: Register Device
on:
  workflow_dispatch:
    inputs:
      device_name:
        required: true
        description: 'Device Name'
        default: ''
      device_type:
        required: true
        description: 'Device Type'
        default: ''
      device_uuid:
        required: true
        description: 'Device UUID'
        default: ''
jobs:
  build:
    steps:
      - uses: actions/checkout@v2
      - name: Register Device
        env:
          DEVICE_NAME: ${{ github.event.inputs.device_name }}
          DEVICE_TYPE: ${{ github.event.inputs.device_type }}
          DEVICE_UUID: ${{ github.event.inputs.device_uuid }}
        run: |
          echo ${{ github.event.inputs.device_name }} ${{ github.event.inputs.device_type }}
